import { tierMeta } from '../format';

// Tier = colour + word, never colour alone (decision 6.3).
export function TierBadge({ tier, size = 'md', title }) {
  const m = tierMeta(tier);
  return (
    <span className={`tier-badge tier-${size}`} style={{ background: m.color, color: m.ink }}
          title={title || m.help}>
      {m.label}
    </span>
  );
}

export function SimBadge() {
  return <span className="sim-badge" title="Virtual node - data generated by the simulator">SIMULATED</span>;
}

export function OfflineBadge() {
  return <span className="offline-badge" title="No packets for 3 heartbeat periods">OFFLINE</span>;
}
