import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api';
import { usePoll, useNow } from '../live';
import {
  ago, fmtDateTime, fmtTime, patternLabel, patternHelp, decodeFlags, RESET_REASONS, tierMeta, hasPatterns,
} from '../format';
import { TierBadge, SimBadge, OfflineBadge } from '../components/Badges';
import { TimeSeriesChart, TierStrip } from '../components/Charts';

const RANGES = [1, 6, 24];
const FIELDS = ['moisture_index', 'tilt_deg', 'tilt_event', 'temp_c', 'rssi'];

export default function NodePage() {
  const { id } = useParams();
  const [hours, setHours] = useState(6);
  const now = useNow(5000);
  const node = usePoll(() => api.node(id), 10000, [id]);
  const tele = usePoll(() => api.telemetry(id, hours, FIELDS), 20000, [id, hours]);
  const tiers = usePoll(() => api.tiers(id, hours), 20000, [id, hours]);

  if (node.error) return <div className="page"><p className="error">Could not load node: {node.error}</p></div>;
  const n = node.data;
  if (!n) return <div className="page"><p className="muted">Loading...</p></div>;

  const to = Date.now();
  const from = to - hours * 3600 * 1000;
  const s = tele.data || {};
  const lossPct = n.packets_received ? (100 * n.packets_lost) / (n.packets_received + n.packets_lost) : 0;
  const flags = decodeFlags(n.sensor_flags);
  const m = tierMeta(n.tier);

  return (
    <div className="page">
      <Link to="/dashboard" className="back">&larr; Dashboard</Link>
      <div className="page-head">
        <h1>{n.name}</h1>
        {n.is_virtual && <SimBadge />}
        {n.online === false && <OfflineBadge />}
        <TierBadge tier={n.tier} />
        <span className="muted">{n.node_type} node · {n.zone_name || 'no zone'} · radio ID {n.radio_id}</span>
      </div>
      {n.is_virtual && (
        <p className="note">This is a virtual node. Its readings are generated by the simulator (tools/simulate.py) and pass through the real pipeline.</p>
      )}

      <div className="cards">
        <section className="card">
          <h2>PCHA assessment</h2>
          <div className="kv"><span>Tier</span><span><TierBadge tier={n.tier} size="sm" /> {m.help}</span></div>
          <div className="kv"><span>Since</span><span>{fmtDateTime(n.tier_since)}</span></div>
          {n.tier === 'no_data' && (
            <div className="kv"><span>Patterns</span><span>Not shown: there is not enough recent data, so the state is unknown (not safe).</span></div>
          )}
          {hasPatterns(n) && (
            <>
              <div className="kv"><span>Moisture</span>
                <span><strong>{patternLabel('moisture', n.moisture_pattern)}</strong> - {patternHelp('moisture', n.moisture_pattern)}</span></div>
              <div className="kv"><span>Tilt</span>
                <span><strong>{patternLabel('tilt', n.tilt_pattern)}</strong> - {patternHelp('tilt', n.tilt_pattern)}</span></div>
            </>
          )}
          <div className="kv"><span>Reason</span><span className="mono small">{n.reason || '—'}</span></div>
          <div className="kv"><span>Checked</span><span>{n.evaluated_at ? `${fmtTime(n.evaluated_at)} (${ago(n.evaluated_at, now)})` : 'not yet'}</span></div>
        </section>

        <section className="card">
          <h2>Health</h2>
          <div className="kv"><span>Status</span><span>{n.online ? 'Online' : 'Offline'} · last seen {ago(n.last_seen_at, now)}</span></div>
          <div className="kv"><span>Battery</span>
            <span>{n.battery_mv ? `${(n.battery_mv / 1000).toFixed(2)} V` : 'not measured (USB powered)'}</span></div>
          <div className="kv"><span>Signal</span><span>{n.rssi != null ? `${n.rssi} dBm RSSI · SNR ${n.snr} dB` : '—'}</span></div>
          <div className="kv"><span>Packets</span>
            <span>{n.packets_received || 0} received · {n.packets_lost || 0} lost ({lossPct.toFixed(1)} %)</span></div>
          <div className="kv"><span>Firmware</span><span>{n.firmware_version ?? '—'} · last restart: {RESET_REASONS[n.last_reset_reason] || '—'}</span></div>
          <div className="kv"><span>Sensor flags</span><span>{flags.length ? flags.join(', ') : 'none'}</span></div>
        </section>
      </div>

      <div className="range">
        <span className="muted small">Show last</span>
        {RANGES.map((h) => (
          <button key={h} className={`btn btn-sm ${h === hours ? 'btn-on' : ''}`} onClick={() => setHours(h)}>{h} h</button>
        ))}
        {tele.error && <span className="error small">Charts not updating: {tele.error}</span>}
      </div>

      <TierStrip history={tiers.data} currentTier={n.tier} from={from} to={to} />
      <div className="charts">
        <TimeSeriesChart title="Soil moisture" unit="index 0-100" series={s.moisture_index}
                         domain={[from, to]} yDomain={[0, 100]} digits={0} />
        <TimeSeriesChart title="Tilt" unit="degrees from vertical" series={s.tilt_deg} events={s.tilt_event}
                         domain={[from, to]} digits={2} note="diamonds = motion bursts" />
        <TimeSeriesChart title="Temperature" unit="°C (accelerometer chip)" series={s.temp_c}
                         domain={[from, to]} digits={1} />
        <TimeSeriesChart title="Radio signal" unit="RSSI dBm" series={s.rssi} domain={[from, to]} digits={0} />
      </div>
    </div>
  );
}
